
persistence:
  enabled: true
  existingClaim: pvc-grafana
service:
  type: NodePort
  port: 80
  targetPort: 3000
  nodePort: 31000

admin:
  existingSecret: "grafana-secret"
  userKey: username
  passwordKey: password

