# Copyright 2019, Oracle Corporation and/or its affiliates.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.

FROM python:3.7

WORKDIR /usr/src/app

COPY scripts/* ./

CMD ["python", "-u", "./server.py"]
