kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv-mysql 
  labels:
    type: local
spec:
  storageClassName: mysql 
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "%PV_ROOT%/monitoring/mysql_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql
  namespace: default
spec:
  storageClassName: mysql 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

