package io.prometheus.wls.rest;
/*
 * Copyright (c) 2017, 2019, Oracle Corporation and/or its affiliates. All rights reserved.
 *
 * Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
 */

/**
 * An exception generated by the web client.
 */
class WebClientException extends RuntimeException {
    WebClientException() {}

    WebClientException(String message) {
        super(message);
    }

    WebClientException(Throwable cause, String message, Object... args) {
        super(formatMessage(message, args), cause);
    }

    private static String formatMessage(String message, Object... args) {
        return String.format(message, args);
    }
}
